### ISSUE TITLE
Training f0_mean IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jerrymatjila** [yl4579/StarGANv2-VC#20]
Training f0_mean IndexError: tuple index out of range

Thanks for this great project. The results are impressive. 

To reproduce the models, I followed training instructions using provided [dataset](https://drive.google.com/file/d/1t7QQbu4YC_P1mv9puA_KgSomSFDsSzD6/view?usp=sharing) and `config.yml`. However, training is throwing the following error:

```bash
$ python train.py --config_path ./Configs/config.yml
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
{'max_lr': 2e-06, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 2725}
[train]:   0%|                                                                              | 0/2725 [00:01<?, ?it/s]
Traceback (most recent call last):
File "/deepmind/experiments/yl4579/starganv2-vc/train.py", line 156, in <module>
main()
File "/storage/usr/conda/envs/starganv2-vc/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/storage/usr/conda/envs/starganv2-vc/lib/python3.9/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/storage/usr/conda/envs/starganv2-vc/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/storage/usr/conda/envs/starganv2-vc/lib/python3.9/site-packages/click/core.py", line 754, in invoke
return __callback(*args, **kwargs)
File "/deepmind/experiments/yl4579/starganv2-vc/train.py", line 125, in main
train_results = trainer._train_epoch()
File "/deepmind/experiments/yl4579/starganv2-vc/trainer.py", line 195, in _train_epoch
g_loss, g_losses_latent = compute_g_loss(
File "/deepmind/experiments/yl4579/starganv2-vc/losses.py", line 106, in compute_g_loss
loss_f0 = f0_loss(F0_fake, F0_real)
File "/deepmind/experiments/yl4579/starganv2-vc/losses.py", line 212, in f0_loss
x_mean = compute_mean_f0(x_f0)
File "/deepmind/experiments/yl4579/starganv2-vc/losses.py", line 203, in compute_mean_f0
f0_mean = f0_mean.expand(f0.shape[-1], f0_mean.shape[0]).transpose(0, 1) # (B, M)
IndexError: tuple index out of range
```
In `config.yml` batch_size is set to 1. 
Any idea how to fix this?

**Comment by yl4579** [comment]
The code was not written with `batch_size=1` in mind, so could you please set `batch_size=2` instead? It is also too noisy for the discriminator to learn anything meaningful, I would say `batch_size` should be at least > 5.
