### ISSUE TITLE
我在使用自己处理数据时，运行代码报错

### ISSUE THREAD

**Issue by love112358** [yl4579/StarGANv2-VC#89]
大家好，请教一个问题，我是使用自己下载的音频文件wav格式，通过作者的方法处理完结束，写入 train_list 和val_list文件后进行训练报错。大家又遇到问题的麻烦帮我看看谢谢
y: torch.Size([5]) tensor([31, 33, 26,  1, 27], device='cuda:0')

idx tensor([0, 1, 2, 3, 4], device='cuda:0')
/opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
[train]:   0%|                                                                                  | 0/3302 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    main()
  File "/home/amax/anaconda3/envs/video_voice_env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/amax/anaconda3/envs/video_voice_env/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/amax/anaconda3/envs/video_voice_env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/amax/anaconda3/envs/video_voice_env/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 133, in main
    train_results = trainer._train_epoch()
  File "/data0/work/groups/models/Voice_Models/StarGANv2-VC/trainer.py", line 177, in _train_epoch
    d_loss, d_losses_latent = compute_d_loss(self.model, self.args.d_loss, x_real, y_org, y_trg, z_trg=z_trg, use_adv_cls=use_adv_cls, use_con_reg=use_con_reg)
  File "/data0/work/groups/models/Voice_Models/StarGANv2-VC/losses.py", line 21, in compute_d_loss
    out = nets.discriminator(x_real, y_org)
  File "/home/amax/anaconda3/envs/video_voice_env_wjx/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data0/work/groups/weijiaxu/models/Voice_Models/StarGANv2-VC/models.py", line 322, in forward
    return self.dis(x, y)
  File "/home/amax/anaconda3/envs/video_voice_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data0/work/groups/models/Voice_Models/StarGANv2-VC/models.py", line 370, in forward
    out = out[idx, y]  # (batch)
RuntimeError: CUDA error: device-side assert triggered

**Comment by love112358** [comment]
问题已经解决： 这里的种类不对  num_domains: 43
